In [1]:
import numpy
import scipy

In [2]:
import GPy

/home/akash/anaconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


warning in stationary: failed to import cython module: falling back to numpy


In [3]:
import matplotlib.pyplot as plt


In [4]:
import numpy as np


In [5]:

X = np.random.uniform(-3.,3.,(20,1))
Y = np.sin(X) + np.random.randn(20,1)*0.05

In [6]:

kernel = GPy.kern.RBF(input_dim=1, variance=1., lengthscale=1.)

In [8]:
GPy.kern.BasisFuncKernel?

In [7]:
m = GPy.models.GPRegression(X,Y,kernel)


In [8]:
from IPython.display import display


In [9]:
display(m)

In [10]:
fig=m.plot()

In [10]:
fig = m.plot(plot_density=True)

In [11]:
plt.show(fig)

In [12]:
m.rbf

In [16]:
m.inducing_inputs

AttributeError: 'GPRegression' object has no attribute 'inducing_inputs'

In [17]:
m.rbf.lengthscale=0.2


In [13]:
print m['.*var']


  index  |             GP_regression.rbf.variance  |  constraints  |  priors
  [0]    |                             1.00000000  |      +ve      |        
  -----  |  GP_regression.Gaussian_noise.variance  |  -----------  |  ------
  [0]    |                             1.00000000  |      +ve      |        


In [20]:
print m['.*rbf']


  index  |     GP_regression.rbf.variance  |  constraints  |  priors
  [0]    |                     1.00000000  |      +ve      |        
  -----  |  GP_regression.rbf.lengthscale  |  -----------  |  ------
  [0]    |                     0.20000000  |      +ve      |        


In [21]:
print m['']

  index  |             GP_regression.rbf.variance  |  constraints  |  priors
  [0]    |                             1.00000000  |      +ve      |        
  -----  |          GP_regression.rbf.lengthscale  |  -----------  |  ------
  [0]    |                             0.20000000  |      +ve      |        
  -----  |  GP_regression.Gaussian_noise.variance  |  -----------  |  ------
  [0]    |                             1.00000000  |      +ve      |        


In [22]:
m.rbf.variance.unconstrain()


array([0])

In [12]:
print m


Name : GP regression
Objective : 23.0437024904
Number of Parameters : 3
Number of Optimization Parameters : 3
Updates : True
Parameters:
  GP_regression.           |  value  |  constraints  |  priors
  rbf.variance             |    1.0  |      +ve      |        
  rbf.lengthscale          |    1.0  |      +ve      |        
  Gaussian_noise.variance  |    1.0  |      +ve      |        


In [13]:
m.optimize()

In [25]:
print m


Name : GP regression
Objective : 20.7696832827
Number of Parameters : 3
Number of Optimization Parameters : 3
Updates : True
Parameters:
  GP_regression.           |           value  |  constraints  |  priors
  rbf.variance             |  0.427466935875  |               |        
  rbf.lengthscale          |  0.269376633988  |      +ve      |        
  Gaussian_noise.variance  |  0.594763577768  |      +ve      |        


In [15]:
m.rbf.lengthscale=0.5

In [16]:
m.rbf.constrain_positive()

In [28]:
m.constrain()

TypeError: constrain() takes at least 2 arguments (1 given)

In [17]:
m.optimize()

In [18]:
print m


Name : GP regression
Objective : -17.9434842324
Number of Parameters : 3
Number of Optimization Parameters : 3
Updates : True
Parameters:
  GP_regression.           |             value  |  constraints  |  priors
  rbf.variance             |    0.700613813349  |      +ve      |        
  rbf.lengthscale          |     1.47652186239  |      +ve      |        
  Gaussian_noise.variance  |  0.00175374758261  |      +ve      |        


In [19]:
m.rbf.variance.unconstrain()

array([0])

In [20]:
plt.show(fig)

In [25]:
X2 = np.random.uniform(-3., 3., (50,2))

In [26]:
ker2 = GPy.kern.Matern52(2, ARD=True) + GPy.kern.White(2)

Y2 = np.sin(X2[:,0:1]) * np.sin(X2[:,1:2]) + np.random.randn(50,1) * 0.05

In [27]:
Y2 = np.sin(X2[:,0:1])*np.sin(X2[:,1:2]) + np.random.randn(50,1)*0.05

In [28]:
print Y2

[[ 0.62116763]
 [-0.31356068]
 [ 0.5712913 ]
 [ 0.09783766]
 [ 0.0878301 ]
 [ 0.74033409]
 [ 0.7321846 ]
 [ 0.10089086]
 [-0.19355634]
 [-0.07766448]
 [ 0.59446614]
 [-0.75694605]
 [ 0.08904307]
 [-0.14635337]
 [-0.57123583]
 [ 0.22372074]
 [-0.43621176]
 [-0.22022348]
 [-0.10842042]
 [-0.28144582]
 [-0.58285561]
 [-0.32650779]
 [ 0.36637913]
 [ 0.13635349]
 [-0.07745277]
 [ 0.28487592]
 [ 0.67078739]
 [-0.50239005]
 [ 0.07727027]
 [-0.19844042]
 [ 0.0856174 ]
 [-0.11202168]
 [-0.47669407]
 [ 0.11171146]
 [-0.72798862]
 [-0.09870527]
 [-0.30833187]
 [ 0.47625678]
 [ 0.57052548]
 [ 0.12852347]
 [ 0.09080222]
 [-0.61505061]
 [-0.99326294]
 [-0.43164542]
 [ 0.30716013]
 [ 0.17549975]
 [-0.69915821]
 [-0.83514555]
 [ 0.07692071]
 [ 0.7306798 ]]


In [29]:
m2 = GPy.models.GPRegression(X2,Y2,ker2)

In [30]:
print m2


Name : GP regression
Objective : 72.1147582268
Number of Parameters : 5
Number of Optimization Parameters : 5
Updates : True
Parameters:
  GP_regression.           |  value  |  constraints  |  priors
  sum.Mat52.variance       |    1.0  |      +ve      |        
  sum.Mat52.lengthscale    |   (2,)  |      +ve      |        
  sum.white.variance       |    1.0  |      +ve      |        
  Gaussian_noise.variance  |    1.0  |      +ve      |        


In [31]:
m2.optimize()

In [22]:
print m2


Name : GP regression
Objective : -21.4654861257
Number of Parameters : 5
Number of Optimization Parameters : 5
Updates : True
Parameters:
  GP_regression.           |              value  |  constraints  |  priors
  sum.Mat52.variance       |     0.428554767373  |      +ve      |        
  sum.Mat52.lengthscale    |               (2,)  |      +ve      |        
  sum.white.variance       |  0.000954928194274  |      +ve      |        
  Gaussian_noise.variance  |  0.000954928194274  |      +ve      |        


In [32]:
fig2 = m2.plot()

In [33]:
plt.show(fig2)

In [25]:
k1 = GPy.kern.RBF(1, 1., 2.)

In [26]:
k2 = GPy.kern.Matern32(input_dim=1, variance=0.5, lengthscale=2.)

In [27]:
k_add = k1 + k2

In [28]:
k_mult = k1*k2

In [29]:
print k_add


  sum.  |  value  |  constraints  |  priors


In [30]:
k_add.plot()

TypeError: reduce() of empty sequence with no initial value

In [31]:
plt.show(k_add)

In [32]:
k_add.plot()

TypeError: reduce() of empty sequence with no initial value

In [33]:
print k_add


  sum.  |  value  |  constraints  |  priors


In [34]:
k_add.rbf.variance = 12.


AttributeError: 'Add' object has no attribute 'rbf'